version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      breaking-security-updates:
        applies-to: security-updates
        update-types:
          - major
      security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch
      breaking-version-updates:
        applies-to: version-updates
        update-types:
          - major
      version-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Europe/Amsterdam
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions:
        patterns:
          - "*"
